### ISSUE TITLE
อยากได้ omise.charges.create,omise.customers.create,omise.customers.list ด้วยได้มั้ยครับ

### ISSUE THREAD

**Issue by nextchanupol** [keeratita/omise_flutter#1]
พอดีผมทำเป็น web view แต่ทีนี้มันไม่สะดวกตอนส่ง api ไปอะครับผม ไม่แน่ใจว่ามันจะมีข้อจำกัดมั้ยครับผม
ขอบคุณมากครับ

**Comment by keeratita** [comment]
ฝั่ง client ทาง Omise เขาให้ใช้แค่ public key เพื่อความปลอดภัยครับ ตัว secret key ควรใช้แค่บนเซิร์ฟเวอร์ครับ
ลองศึกษาเอกสารความปลอดภ้ยเพิ่มเติมดูนะครับผม :) 

- [https://www.omise.co/th/security-best-practices/thailand](https://www.omise.co/th/security-best-practices/thailand)
- [https://www.omise.co/th/api-authentication/thailand#secret-key](https://www.omise.co/th/api-authentication/thailand#secret-key)
